[toolchain]
anchor_version = "0.32.0"

[features]
seeds = true
skip-lint = false

[programs.devnet]
solanablik = "AqdVcH7aYHXtWCQbkEweCDoXGR8qMn4pdKhWScbMcyNv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
